### ISSUE TITLE
[BUG] - Stuck Scanning Connections

### ISSUE THREAD

**Issue by ondrovic** [WebDB-App/app#42]
**Describe the bug**
Brand new docker compose instance, with mysql running in same stack

**To Reproduce**

1. Using the following

<details>
<summary>docker-compose.yml</summary>

```
  services:
  db:
    image: mysql:latest
    restart: always
    env_file: "./.env"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./mysql_data:/var/lib/mysql
      
    webdb:
    image: webdb/app:latest
    restart: always
    ports:
      - "127.0.0.1:22071:22071"
    volumes:
      - ./.webdb:/usr/src/app/static/version
    depends_on:
      - db
  volumes:
     mysql_data:
     webdb:
```
</details>

<details>
<summary>.env</summary>

```
MYSQL_ROOT_PASSWORD=<changeme>
MYSQL_DATABASE="db_name"
MYSQL_USER=user
MYSQL_PASSWORD=<changeme>
MYSQL_PORT=3306
```
</details>

2. Run

```bash
 docker compose up -d
 ```

3. Once container is up and running
    
    * Navigate to
       
       * [Webdb](http://localhost:22071)
4. Observer the infinite loop on `Scanning Connections`

**Expected behavior**
Should list the found connections and allow you to connect to them

**Screenshots**
<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/550d5f0b-b0f3-412e-983a-76623742e388)

</details>

**Additional context**
<details>
<summary> Console errors </summary>

```
Error: Uncaught (in promise): W: {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":"/api/server/connect","ok":false,"name":"HttpErrorResponse","message":"Http failure response for /api/server/connect: 0 Unknown Error","error":{"isTrusted":true}}
```
```
Failed to load resource: net::ERR_EMPTY_RESPONSE     :22071/api/connect:1
```
</details>

<details>
<summary>Scan API Results</summary>

```json
[
    {
        "wrapper": "MongoDB",
        "host": "host.docker.internal",
        "port": 27015
    },
    {
        "wrapper": "MySQL",
        "host": "host.docker.internal",
        "port": 3306
    }
]
```
</details>

<details>
<summary>Connect API Results</summary>

```json
{
  "wrapper": "MongoDB",
  "host": "host.docker.internal",
  "port": 27015,
  "name": "undefined@host.docker.internal:27015",
  "scanned": true,
  "driver": {},
  "params": { "serverSelectionTimeoutMS": 2000, "authSource": "admin" },
  "dbs": [],
  "relations": [],
  "indexes": [],
  "complexes": {},
  "isLoading": false
}
```

```json
{
  "wrapper": "MySQL",
  "host": "host.docker.internal",
  "port": 3306,
  "name": "undefined@host.docker.internal:3306",
  "scanned": true,
  "driver": {},
  "params": {
    "dateStrings": true,
    "multipleStatements": true,
    "supportBigNumbers": true,
    "bigNumberStrings": true
  },
  "dbs": [],
  "relations": [],
  "indexes": [],
  "complexes": {},
  "isLoading": false
}
```
</details>
